[[pages]]
path = "/"
screenshotTimestamp = "2026-03-18T17:38:43Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/AZLbuqo"
