[[pages]]
path = "/__mockup/preview/maze-ui-redesign/StartScreen"
screenshotTimestamp = "2026-03-18T17:44:15Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/0HVSD3O"

[[pages]]
path = "/__mockup/preview/maze-ui-redesign/GameOver"
screenshotTimestamp = "2026-03-18T17:44:17Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/hTHAdKy"

[[pages]]
path = "/preview/maze-ui-redesign/StartScreen"
screenshotTimestamp = "2026-03-18T17:44:40Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/Sq4yq54"

[[pages]]
path = "/preview/maze-ui-redesign/GameOver"
screenshotTimestamp = "2026-03-18T17:44:43Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/qCh24De"

[[pages]]
path = "/preview/maze-ui-redesign/HUD"
screenshotTimestamp = "2026-03-18T17:44:53Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/KkQT3rQ"

[[pages]]
path = "/preview/maze-ui-redesign/LevelComplete"
screenshotTimestamp = "2026-03-18T17:44:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/28a79b4a-45dd-47a4-94f1-8cdaabb18c92/7aa05b94-311d-4c7b-8316-ddd94c1676c8/mepcFlv"
