// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/maze-ui-redesign/GameOver.tsx": () => import("../components/mockups/maze-ui-redesign/GameOver.tsx"),
  "./components/mockups/maze-ui-redesign/HUD.tsx": () => import("../components/mockups/maze-ui-redesign/HUD.tsx"),
  "./components/mockups/maze-ui-redesign/LevelComplete.tsx": () => import("../components/mockups/maze-ui-redesign/LevelComplete.tsx"),
  "./components/mockups/maze-ui-redesign/StartScreen.tsx": () => import("../components/mockups/maze-ui-redesign/StartScreen.tsx")
};
